Headline
Every startup wants growth. Most of them start by hiring for channels. An ads person, an SEO person, maybe a social media manager. Before anyone's figured out why people should care in the first place. I've seen this play out enough times to know that channels without a story just burns money faster. So I work the other way. Start with what makes someone stop and pay attention, then figure out how to get that in front of more people.
About
I studied mechanical engineering at NIT Warangal. Loved how engineers think in systems, didn't love where the career was headed. Joined Capgemini after college, learned how large organizations operate, and figured out pretty quickly that wasn't for me either. After I quit, I didn't have a clear next step. Spent time learning logo and brand design, started freelancing because I didn't have anything else going on, and eventually turned that into Untitled Creatives, a full agency. That's where I noticed something about myself. I kept getting pulled toward the strategy and execution side of projects, not just putting together brand guidelines. But I didn't have a real understanding of how startups operate under the hood. Took the CAT, scored 99.3 percentile, and picked Mesa School of Business. Not the highest-ranked option on paper, but it's in Bengaluru, rooted in the startup ecosystem, and full of people actually building companies.
Why me?
I pick up context fast. Went from knowing nothing about the silver jewellery market to delivering a 16-slide strategy deck with 83 cited sources for GIVA in days. I also build things myself. If I need a dashboard or an AI agent, I'll put it together with n8n and OpenAI rather than writing a brief and waiting for someone else. The engineering background helps too. I think in systems, not channels. That's how I ended up finding that 70% of a company's customer health scores were overestimated while everyone else was treating the numbers as solid.
About me out of work
Outside of work, I ride motorcycles. Currently stuck in the research spiral of picking my next motorcycle. I watch cricket, F1, and tennis religiously, and I'll play badminton, chess, or poker any chance I get. I read a lot of fiction, no genre loyalty there either. I watch everything from sci-fi and fantasy to comedy to brainrot Telugu action movies that require absolutely no thinking. Music is the same story. Anything across any language, any genre. I will sing along to all of it whether or not I should be.
Closing
I want to join a startup and own the full journey from "some people know who we are" to "we know exactly how we grow." If you're hiring or know someone who is, let's talk.
Email: srikarpandrangi121@gmail.com
LinkedIn: www.linkedin.com/in/srikarpandrangi
Phone: 9676114683